#!/bin/bash
TARGET="/var/www/html"
GIT_DIR="/var/www/project.git"
BRANCH="master"

while read oldrev newrev ref
do
	if [ "$ref" = "refs/heads/$BRANCH" ];
	then
		git --work-tree=$TARGET --git-dir=$GIT_DIR checkout -f $BRANCH
		echo "Done!"
	else
		echo "Everything is up-to-date"
	fi
done
