# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: pcarolei <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2019/02/14 16:58:20 by pcarolei          #+#    #+#              #
#    Updated: 2019/02/14 16:58:24 by pcarolei         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = ft_cat

all:
	@gcc -Wall -Wextra -Werror ./ft_cat.c ./ft_helper_funcs.c ./ft_display_error_message.c -o $(NAME)

clean:
	@rm -f $(NAME)

fclean: clean
	@rm -f $(NAME)
