# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: pcarolei <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2019/02/14 14:29:09 by pcarolei          #+#    #+#              #
#    Updated: 2019/04/02 18:27:42 by pcarolei         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

SRC_NAME = ft_display_file.c
NAME = ft_display_file

all:
	@gcc -Wall -Wextra -Werror $(SRC_NAME) -o $(NAME)

clean:
	@rm -f ft_display_file.o

fclean: clean
	@rm -f $(NAME)
